[build]
  publish = "."
  command = "npm start"

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/brands.html"
  to = "/brands"
  status = 301

[[redirects]]
  from = "/agents.html"
  to = "/agents"
  status = 301

[[redirects]]
  from = "/kontakt.html"
  to = "/kontakt"
  status = 301

[[redirects]]
  from = "/partnerprogramm.html"
  to = "/partnerprogramm"
  status = 301

[[redirects]]
  from = "/impressum.html"
  to = "/impressum"
  status = 301

# Rewrites für saubere URLs
[[redirects]]
  from = "/brands"
  to = "/brands.html"
  status = 200

[[redirects]]
  from = "/agents"
  to = "/agents.html"
  status = 200

[[redirects]]
  from = "/kontakt"
  to = "/kontakt.html"
  status = 200

[[redirects]]
  from = "/partnerprogramm"
  to = "/partnerprogramm.html"
  status = 200

[[redirects]]
  from = "/impressum"
  to = "/impressum.html"
  status = 200

# Headers für bessere Performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"




